[green_agent]
agentbeats_id = "019bbbcc-ab5d-7600-bb25-b05592423203"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_API_BASE = "${OPENAI_API_BASE}", LLM_MODEL = "${LLM_MODEL}" }

[[participants]]
agentbeats_id = "019bc88d-d2d0-7ff3-a5a6-ac200b1475f1"
name = "shopper"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_API_BASE = "${OPENAI_API_BASE}", LLM_MODEL = "${LLM_MODEL}" }

[config]
num_tasks = 8
task_types = ["all"]
timeout_per_task = 300