[green_agent]
agentbeats_id = "019bbbcc-ab5d-7600-bb25-b05592423203"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_API_BASE = "${OPENAI_API_BASE}", LLM_MODEL = "${LLM_MODEL}" }

[[participants]]
agentbeats_id = "019bbbe2-5af6-79d2-8932-d59127888f8f"
name = "shopper"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_API_BASE = "${OPENAI_API_BASE}", LLM_MODEL = "${LLM_MODEL}" }

#trigger assessment 6
[config]
num_tasks = 10
task_types = ["all"]
timeout_per_task = 300
